[versions]
activityCompose = "1.11.0"
agp = "8.13.0"
androidCompileSdk = "36"
androidMinSdk = "29"
androidTargetSdk = "36"
appNamespace = "cz.jvyh.o2.scratch"
appVersionCode = "1"
appVersionName = "1.0.0"
composeMultiplatform = "1.9.0-alpha03"
coreKtx = "1.17.0"
kermit = "2.0.8"
koin = "4.1.1"
kotest = "6.0.3"
kotlin = "2.2.20"
kotlinxCoroutines = "1.10.2"
ktor = "3.3.0" # 3.2.0 introduced "com.android.tools.r8.internal.Qf: Space characters in SimpleName 'use streaming syntax' are not allowed prior to DEX version 040"
lifecycle = "2.9.4"
mockk = "1.14.6"
navigation = "2.9.0"
slf4j = "2.0.17"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" } # no jetbrains variant
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-navigation-common = { module = "org.jetbrains.androidx.navigation:navigation-common", version.ref = "navigation" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-navigation-runtime = { module = "org.jetbrains.androidx.navigation:navigation-runtime", version.ref = "navigation" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-androidx-navigation = { module = "io.insert-koin:koin-androidx-navigation" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-core-viewmodel = { module = "io.insert-koin:koin-core-viewmodel" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-java = { module = "io.ktor:ktor-client-java" } # JVM, supports both HTTP/2 and WebSockets
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp" } # JVM/Android engine, supports both HTTP/2 and WebSockets
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
# Tests
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" } # Base testing framework
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" } # Expressive assertions framework
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" } # Coroutines testing
mockk = { module = "io.mockk:mockk", version.ref = "mockk" } # Mocking framework

[bundles]
koin-common = [
    "koin-compose",
    "koin-compose-viewmodel",
    "koin-core",
    "koin-core-viewmodel"
]
koin-android = [
    "koin-android",
    "koin-androidx-compose",
    "koin-androidx-navigation"
]
ktor-common = [
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-client-logging",
    "ktor-serialization-kotlinx-json"
]
lifecycle-common = [
    "androidx-lifecycle-runtime",
    "androidx-lifecycle-viewmodel"
]
lifecycle-android = [
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-viewmodel-compose"
]
navigation-common = [
    "androidx-navigation-common",
    "androidx-navigation-runtime"
]
unit-testing-common = [
    "kotlin-test",
    "kotest-assertions-core",
    "kotlinx-coroutines-test",
    "mockk"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" } # for Ktor